//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.FAQPlusPlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.FAQPlusPlus.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new question details.
        /// </summary>
        public static string AddQuestionSubtitle {
            get {
                return ResourceManager.GetString("AddQuestionSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Respuesta:**.
        /// </summary>
        public static string AnswerTitle {
            get {
                return ResourceManager.GetString("AnswerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta un experto.
        /// </summary>
        public static string AskAnExpertButtonText {
            get {
                return ResourceManager.GetString("AskAnExpertButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta un experto.
        /// </summary>
        public static string AskAnExpertDisplayText {
            get {
                return ResourceManager.GetString("AskAnExpertDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe aquí tu pregunta  (500 caracteres máximo).
        /// </summary>
        public static string AskAnExpertPlaceholderText {
            get {
                return ResourceManager.GetString("AskAnExpertPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El experto se pondrá en contacto contigo a través de Teams..
        /// </summary>
        public static string AskAnExpertSubheaderText {
            get {
                return ResourceManager.GetString("AskAnExpertSubheaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si no puedo contestar tu pregunta, se la enviaré a un experto..
        /// </summary>
        public static string AskAnExpertText2 {
            get {
                return ResourceManager.GetString("AskAnExpertText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta un experto.
        /// </summary>
        public static string AskAnExpertTitleText {
            get {
                return ResourceManager.GetString("AskAnExpertTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu pregunta ha sido asignada a un experto. Se pondrán en contacto contigo pronto..
        /// </summary>
        public static string AssignedTicketUserNotification {
            get {
                return ResourceManager.GetString("AssignedTicketUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignada.
        /// </summary>
        public static string AssignedUserNotificationStatus {
            get {
                return ResourceManager.GetString("AssignedUserNotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignarla a mi.
        /// </summary>
        public static string AssignToMeActionChoiceTitle {
            get {
                return ResourceManager.GetString("AssignToMeActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackButton.
        /// </summary>
        public static string BackButtonCommandText {
            get {
                return ResourceManager.GetString("BackButtonCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar status.
        /// </summary>
        public static string ChangeStatusButtonText {
            get {
                return ResourceManager.GetString("ChangeStatusButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with {0}.
        /// </summary>
        public static string ChatTextButton {
            get {
                return ResourceManager.GetString("ChatTextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string CloseActionChoiceTitle {
            get {
                return ResourceManager.GetString("CloseActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrada:.
        /// </summary>
        public static string ClosedFactTitle {
            get {
                return ResourceManager.GetString("ClosedFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta consulta fue cerrada..
        /// </summary>
        public static string ClosedTicketUserNotification {
            get {
                return ResourceManager.GetString("ClosedTicketUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrada.
        /// </summary>
        public static string ClosedUserNotificationStatus {
            get {
                return ResourceManager.GetString("ClosedUserNotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No encontré una respuesta apropiada para tu pregunta. Deseas preguntarle a un experto?.
        /// </summary>
        public static string CustomMessage {
            get {
                return ResourceManager.GetString("CustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creada:.
        /// </summary>
        public static string DateCreatedDisplayFactTitle {
            get {
                return ResourceManager.GetString("DateCreatedDisplayFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} at {1}.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item? The question and answer will both be deleted..
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted by {0}.
        /// </summary>
        public static string DeletedQnaPair {
            get {
                return ResourceManager.GetString("DeletedQnaPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción:.
        /// </summary>
        public static string DescriptionFact {
            get {
                return ResourceManager.GetString("DescriptionFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Description (Markdown supported).
        /// </summary>
        public static string DescriptionLabelText {
            get {
                return ResourceManager.GetString("DescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter information (500 characters max).
        /// </summary>
        public static string DescriptionPlaceholderText {
            get {
                return ResourceManager.GetString("DescriptionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit question details.
        /// </summary>
        public static string EditQuestionSubtitle {
            get {
                return ResourceManager.GetString("EditQuestionSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be empty..
        /// </summary>
        public static string EmptyDescriptionErrorText {
            get {
                return ResourceManager.GetString("EmptyDescriptionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image url can not be empty..
        /// </summary>
        public static string EmptyImageUrlErrorText {
            get {
                return ResourceManager.GetString("EmptyImageUrlErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question text cannot be empty..
        /// </summary>
        public static string EmptyQuestionErrorText {
            get {
                return ResourceManager.GetString("EmptyQuestionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be empty..
        /// </summary>
        public static string EmptyTitleErrorText {
            get {
                return ResourceManager.GetString("EmptyTitleErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string EntryCreatedByText {
            get {
                return ResourceManager.GetString("EntryCreatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** ha compartido feedback.
        /// </summary>
        public static string FeedbackAlertText {
            get {
                return ResourceManager.GetString("FeedbackAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe aquí tu feedback. (500 caracteres máximo).
        /// </summary>
        public static string FeedbackDescriptionPlaceholderText {
            get {
                return ResourceManager.GetString("FeedbackDescriptionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback (Requerido).
        /// </summary>
        public static string FeedbackRatingRequired {
            get {
                return ResourceManager.GetString("FeedbackRatingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, ayuda al equipo de expertos a entrenarme compartiendo tu feedback..
        /// </summary>
        public static string FeedbackText1 {
            get {
                return ResourceManager.GetString("FeedbackText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazme una pregunta relacionada a temas de tecnología..
        /// </summary>
        public static string FunctionCardText1 {
            get {
                return ResourceManager.GetString("FunctionCardText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puedes hacerme una pregunta escribiendo abajo, haré lo posibe para ayudarte..
        /// </summary>
        public static string FunctionCardText2 {
            get {
                return ResourceManager.GetString("FunctionCardText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a la conversación original.
        /// </summary>
        public static string GoToOriginalThreadButtonText {
            get {
                return ResourceManager.GetString("GoToOriginalThreadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver detalles.
        /// </summary>
        public static string GoToThread {
            get {
                return ResourceManager.GetString("GoToThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfecho.
        /// </summary>
        public static string HelpfulRatingText {
            get {
                return ResourceManager.GetString("HelpfulRatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML tags are not supported..
        /// </summary>
        public static string HTMLErrorText {
            get {
                return ResourceManager.GetString("HTMLErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image URL.
        /// </summary>
        public static string ImageLabelText {
            get {
                return ResourceManager.GetString("ImageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter image URL (200 characters max).
        /// </summary>
        public static string ImageUrlPlaceholderText {
            get {
                return ResourceManager.GetString("ImageUrlPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image URL is not valid..
        /// </summary>
        public static string InvalidImageUrlErrorText {
            get {
                return ResourceManager.GetString("InvalidImageUrlErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect URL is not valid..
        /// </summary>
        public static string InvalidRedirectUrlText {
            get {
                return ResourceManager.GetString("InvalidRedirectUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last edited by.
        /// </summary>
        public static string LastEditedText {
            get {
                return ResourceManager.GetString("LastEditedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title field is mandatory..
        /// </summary>
        public static string MandatoryTitleFieldText {
            get {
                return ResourceManager.GetString("MandatoryTitleFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually added question.
        /// </summary>
        public static string ManuallyAddedQuestionMessage {
            get {
                return ResourceManager.GetString("ManuallyAddedQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necesita mejorar.
        /// </summary>
        public static string NeedsImprovementRatingText {
            get {
                return ResourceManager.GetString("NeedsImprovementRatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The messaging extension can only be invoked from the channel in which the  app is installed.
        /// </summary>
        public static string NonSMEErrorText {
            get {
                return ResourceManager.GetString("NonSMEErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No satisfecho.
        /// </summary>
        public static string NotHelpfulRatingText {
            get {
                return ResourceManager.GetString("NotHelpfulRatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He compartido tu pregunta con los expertos. Se pondrán en contacto contigo a través de Teams en breve..
        /// </summary>
        public static string NotificationCardContent {
            get {
                return ResourceManager.GetString("NotificationCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open article.
        /// </summary>
        public static string OpenArticle {
            get {
                return ResourceManager.GetString("OpenArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Fields.
        /// </summary>
        public static string OptionalFieldDisplayText {
            get {
                return ResourceManager.GetString("OptionalFieldDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PreviewButtonText {
            get {
                return ResourceManager.GetString("PreviewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question already exist. please add different question..
        /// </summary>
        public static string QuestionAlreadyExistsErrorText {
            get {
                return ResourceManager.GetString("QuestionAlreadyExistsErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregunta del usuario:.
        /// </summary>
        public static string QuestionAskedFactTitle {
            get {
                return ResourceManager.GetString("QuestionAskedFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** esta pidiendo ayuda.
        /// </summary>
        public static string QuestionForExpertSubHeaderText {
            get {
                return ResourceManager.GetString("QuestionForExpertSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Question.
        /// </summary>
        public static string QuestionLabelText {
            get {
                return ResourceManager.GetString("QuestionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter information (100 characters max).
        /// </summary>
        public static string QuestionPlaceholderText {
            get {
                return ResourceManager.GetString("QuestionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Pregunta:** {0}.
        /// </summary>
        public static string QuestionTitle {
            get {
                return ResourceManager.GetString("QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating obligatorio.
        /// </summary>
        public static string RatingMandatoryText {
            get {
                return ResourceManager.GetString("RatingMandatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirection URL.
        /// </summary>
        public static string RedirectionLabelText {
            get {
                return ResourceManager.GetString("RedirectionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter information (200 characters max).
        /// </summary>
        public static string RedirectionUrlPlaceholderText {
            get {
                return ResourceManager.GetString("RedirectionUrlPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reabrir.
        /// </summary>
        public static string ReopenActionChoiceTitle {
            get {
                return ResourceManager.GetString("ReopenActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reabrir y asignarla a mi.
        /// </summary>
        public static string ReopenAssignToMeActionChoiceTitle {
            get {
                return ResourceManager.GetString("ReopenAssignToMeActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu consulta ha sido abierta nuevamente. Un experto se comunicará contigo pronto..
        /// </summary>
        public static string ReopenedTicketUserNotification {
            get {
                return ResourceManager.GetString("ReopenedTicketUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquí lo que encontré:.
        /// </summary>
        public static string ResponseHeaderText {
            get {
                return ResourceManager.GetString("ResponseHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string ResultsFeedbackText {
            get {
                return ResourceManager.GetString("ResultsFeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartir feedback.
        /// </summary>
        public static string ShareFeedbackButtonText {
            get {
                return ResourceManager.GetString("ShareFeedbackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartir feedback.
        /// </summary>
        public static string ShareFeedbackDisplayText {
            get {
                return ResourceManager.GetString("ShareFeedbackDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartir feedback.
        /// </summary>
        public static string ShareFeedbackTitleText {
            get {
                return ResourceManager.GetString("ShareFeedbackTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen (50 caracteres máximo).
        /// </summary>
        public static string ShowCardTitleText {
            get {
                return ResourceManager.GetString("ShowCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta consulta ha sido asignada a {0}..
        /// </summary>
        public static string SMEAssignedStatus {
            get {
                return ResourceManager.GetString("SMEAssignedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta consulta fue cerrada. Cerrada por {0}..
        /// </summary>
        public static string SMEClosedStatus {
            get {
                return ResourceManager.GetString("SMEClosedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string SMEFeedbackHeaderText {
            get {
                return ResourceManager.GetString("SMEFeedbackHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta consulta no esta asignada. Modificada por {0}..
        /// </summary>
        public static string SMEOpenedStatus {
            get {
                return ResourceManager.GetString("SMEOpenedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignada a {0}.
        /// </summary>
        public static string SMETicketAssignedStatus {
            get {
                return ResourceManager.GetString("SMETicketAssignedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrada.
        /// </summary>
        public static string SMETicketClosedStatus {
            get {
                return ResourceManager.GetString("SMETicketClosedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin asignar.
        /// </summary>
        public static string SMETicketUnassignedStatus {
            get {
                return ResourceManager.GetString("SMETicketUnassignedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RE: {0}.
        /// </summary>
        public static string SMEUserChatMessage {
            get {
                return ResourceManager.GetString("SMEUserChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        public static string StatusFactTitle {
            get {
                return ResourceManager.GetString("StatusFactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle (Markdown supported).
        /// </summary>
        public static string SubtitleLabelText {
            get {
                return ResourceManager.GetString("SubtitleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter information (20 characters max).
        /// </summary>
        public static string SubtitlePlaceholderText {
            get {
                return ResourceManager.GetString("SubtitlePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The optional fields below can be used to add additional details to the answer..
        /// </summary>
        public static string SuggestedText {
            get {
                return ResourceManager.GetString("SuggestedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team tour.
        /// </summary>
        public static string TakeATeamTourButtonText {
            get {
                return ResourceManager.GetString("TakeATeamTourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomar el tour.
        /// </summary>
        public static string TakeATourButtonText {
            get {
                return ResourceManager.GetString("TakeATourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haz click en chat con usuario para iniciar una conversación 1:1..
        /// </summary>
        public static string TeamChatContent {
            get {
                return ResourceManager.GetString("TeamChatContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comienza un chat con el usuario.
        /// </summary>
        public static string TeamChatHeaderText {
            get {
                return ResourceManager.GetString("TeamChatHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I don&apos;t support bot commands in the Team. Here is a quick tour of how I can help..
        /// </summary>
        public static string TeamCustomMessage {
            get {
                return ResourceManager.GetString("TeamCustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puedes ver aquellas preguntas que el bot no pudo contestarle a los usuarios..
        /// </summary>
        public static string TeamNotificationContent {
            get {
                return ResourceManager.GetString("TeamNotificationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibir notificaciones de los usuarios..
        /// </summary>
        public static string TeamNotificationHeaderText {
            get {
                return ResourceManager.GetString("TeamNotificationHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcar las consultas como asignadas o cerradas para mantener control de las consultas atendidas..
        /// </summary>
        public static string TeamTicketSystemContent {
            get {
                return ResourceManager.GetString("TeamTicketSystemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage queries.
        /// </summary>
        public static string TeamTicketSystemHeaderText {
            get {
                return ResourceManager.GetString("TeamTicketSystemHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias por tu feedback! Lo he compartido con los expertos para que me ayuden a aprender y mejorar..
        /// </summary>
        public static string ThankYouTextContent {
            get {
                return ResourceManager.GetString("ThankYouTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo:.
        /// </summary>
        public static string TitleFact {
            get {
                return ResourceManager.GetString("TitleFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title (Markdown supported).
        /// </summary>
        public static string TitleLabelText {
            get {
                return ResourceManager.GetString("TitleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe aquí la información (50 caracteres máximo).
        /// </summary>
        public static string TitlePlaceholderText {
            get {
                return ResourceManager.GetString("TitlePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen (Obligatorio).
        /// </summary>
        public static string TitleRequiredText {
            get {
                return ResourceManager.GetString("TitleRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desasignar.
        /// </summary>
        public static string UnassignActionChoiceTitle {
            get {
                return ResourceManager.GetString("UnassignActionChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin asignar.
        /// </summary>
        public static string UnassignedUserNotificationStatus {
            get {
                return ResourceManager.GetString("UnassignedUserNotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update history.
        /// </summary>
        public static string UpdateHistoryButtonText {
            get {
                return ResourceManager.GetString("UpdateHistoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string UpdateHistoryDateHeaderText {
            get {
                return ResourceManager.GetString("UpdateHistoryDateHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name|Action|Date.
        /// </summary>
        public static string UpdateHistoryHeadersText {
            get {
                return ResourceManager.GetString("UpdateHistoryHeadersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver respuesta al usuario.
        /// </summary>
        public static string ViewArticleButtonText {
            get {
                return ResourceManager.GetString("ViewArticleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for some time, updates to this question: &quot;{0}&quot; will be available in short time..
        /// </summary>
        public static string WaitMessage {
            get {
                return ResourceManager.GetString("WaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Updates are made every few minutes.
        /// </summary>
        public static string WaitMessageAnswer {
            get {
                return ResourceManager.GetString("WaitMessageAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saludos Equipo, Soy el TMD Chatbot que ayuda a sus compañeros al contestar sus preguntas relacionadas a tecnología. Aquellas preguntas que no pueda contestar se las haré llegar para que puedan ayudar al usuario directamente. 
        ///.
        /// </summary>
        public static string WelcomeTeamCardContent {
            get {
                return ResourceManager.GetString("WelcomeTeamCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
